# Generated by Django 6.0.4 on 2026-05-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelkit',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
