# Generated by Django 6.0.4 on 2026-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('AB1', 'Action Base 1'), ('AB2', 'Action Base 2'), ('AB4', 'Action Base 4'), ('AB5', 'Action Base 5')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
